version: '3.8'
services:
    postgres-fs-dev:
        container_name: postgres-fs-dev
        image: postgres:15-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DATABASE}
        ports:
            - 5410:5432
        volumes:
            - fs-data-dev:/var/lib/postgresql/data
        networks:
            - app-network

volumes:
    fs-data-dev:
        name: fs-data-dev
networks:
    app-network:
        name: app-network
