version: '3.8'
services:
    7a-fs-api-stag:
        container_name: 7a-fs-api-stag
        image: qkitsoftware/7a-fs-api:${IMAGE_STAG_TAG}
        restart: always
        networks:
            - app-network
            - web
        ports:
            #- 8512:${PORT}
            - 8513:9229
        depends_on:
            - postgres-fs-stag
        environment:
            # POSTGRES
            - POSTGRES_HOST=postgres-fs-stag
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=${POSTGRES_DATABASE}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
            - PORT=${PORT}
            - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
            - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
            - ACCESS_TOKEN_EXPIRE_TIME=${ACCESS_TOKEN_EXPIRE_TIME}
            - REFRESH_TOKEN_EXPIRE_TIME=${REFRESH_TOKEN_EXPIRE_TIME}

            # mail
            - MAIL_HOST=${MAIL_HOST}
            - MAIL_PORT=${MAIL_PORT}
            - MAIL_FROM=${MAIL_FROM}
            - MAIL_USER=${MAIL_USER}
            - MAIL_PASSWORD=${MAIL_PASSWORD}

            - FRONT_END_URL=http://localhost:3000

            # Docker image version
            - IMAGE_STAG_TAG=latest
            - IMAGE_PROD_TAG=latest

            # Cloudinary
            - CLOUDINARY_CLOUDNAME=dtxtzn5ii
            - CLOUDINARY_CLOUD_APIKEY=797967155671386
            - CLOUDINARY_CLOUD_APISECRET=B7vCMeaP2OSRr6Q19jetHOYIQr8
            - CLOUDINARY_CLOUD_PUBLICDIR=public/feedback-system
            - CLOUDINARY_CLOUD_PRIVATEDIR=private/feedback-system

            - MINUTE_WAIT_FORGOT_PASSWORD=1
        labels:
            - traefik.enable=true
            - traefik.docker.network=web
            #- traefik.http.routers.fs-api-stag-http.rule=Host(`fs-stag.qkit.vn`) && (PathPrefix(`/api`) || PathPrefix(`/docs`))
            #- traefik.http.routers.fs-api-stag-http.entrypoints=web
            #- traefik.http.routers.fs-api-stag-http.middlewares=api-stripping
            #- traefik.http.routers.qet-api-http.priority=5

            - traefik.http.routers.fs-api-stag-https.rule=Host(`fs-stag.qkit.vn`) && (PathPrefix(`/api`) || PathPrefix(`/docs`))
            - traefik.http.routers.fs-api-stag-https.entrypoints=websecure
            #- traefik.http.routers.fs-api-stag-https.service=7a-fs-api-stag
            - traefik.http.services.fs-api-stag.loadbalancer.server.port=${PORT}
            - traefik.http.routers.fs-api-stag-https.middlewares=api-stripping@file  
            #- traefik.http.routers.qet-api-https.priority=5

    postgres-fs-stag:
        container_name: postgres-fs-stag
        image: postgres:15-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DATABASE}
        ports:
            - 5412:5432
        volumes:
            - fs-data-stag:/var/lib/postgresql/data
        networks:
            - app-network

volumes:
    fs-data-stag:
        name: fs-data-stag
networks:
    app-network:
        name: app-network
    web:
        external: true
