version: '3.8'
services:
    7a-fs-api-stag:
        container_name: 7a-fs-api-stag
        image: qkitsoftware/7a-fs-api:${IMAGE_STAG_TAG}
        restart: always
        networks:
            - app-network
        ports:
            - 8512:${PORT}
            - 8513:9229
        depends_on:
            - postgres-fs-stag
        environment:
            # POSTGRES
            - POSTGRES_HOST=postgres-fs-stag
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=${POSTGRES_DATABASE}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
            - PORT=${PORT}
            - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
            - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
            - ACCESS_TOKEN_EXPIRE_TIME=${ACCESS_TOKEN_EXPIRE_TIME}
            - REFRESH_TOKEN_EXPIRE_TIME=${REFRESH_TOKEN_EXPIRE_TIME}

            # mail
            - MAIL_HOST=${MAIL_HOST}
            - MAIL_PORT=${MAIL_PORT}
            - MAIL_FROM=${MAIL_FROM}
            - MAIL_USER=${MAIL_USER}
            - MAIL_PASSWORD=${MAIL_PASSWORD}

    postgres-fs-stag:
        container_name: postgres-fs-stag
        image: postgres:15
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DATABASE}
        ports:
            - 5412:5432
        volumes:
            - fs-data-stag:/var/lib/postgresql/data
        networks:
            - app-network

volumes:
    fs-data-stag:
        name: fs-data-stag
networks:
    app-network:
        name: app-network
