export enum AttributeType {
    TEXT_BOX = 'TEXT_BOX',
    PARAGRAPH = 'PARAGRAPH',
    CHECKBOX_BUTTON = 'CHECKBOX_BUTTON',
    RADIO_BUTTON = 'RADIO_BUTTON',
    DROPDOWN = 'DROPDOWN',
    FILE_UPLOAD = 'FILE_UPLOAD',
    STAR = 'STAR',
    CHECKBOX_GRID = 'CHECKBOX_GRID',
    RADIO_GRID = 'RADIO_GRID',
}
