name: Docker CI/CD Pipeline

# Xác định sự kiện trigger cho pipeline, trong trường hợp này là push lên nhánh develop
on:
    push:
        branches:
            - staging

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              # Sử dụng action "checkout" để sao copy code từ repository vào máy ảo Ubuntu
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_SECRET }}

            - name: docker build image
              uses: docker/setup-buildx-action@v3

            - name: docker push image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: qkitsoftware/7a-fs-api:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

    # Job 2: Deploy
    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to QKIT server
              uses: appleboy/ssh-action@v0.1.4
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd projects/qkit-7a-feedback-backend/
                      sh ./scripts/docker-run-stag.sh
